ALARM_NOTIFY_TOPIC = "arn:aws:sns:yourtopic"
REQUIRED_EC2ALARM_TEMPLATES = [
  {
    "alarm_name": "CPU overload",
    "namespace": "AWS/EC2",
    "metric_name": "CPUUtilization",
    "dimensions": [{"name": "InstanceId", "value": "replace_instance_id_at_runtime"}],
    "threshold": 90,
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "alarm_actions": [ALARM_NOTIFY_TOPIC],
    "evaluation_periods": 1,
    "period": 300,
    "statistic": "Average",
  },
  {
    "alarm_name": "status check failed",
    "namespace": "AWS/EC2",
    "metric_name": "StatusCheckFailed",
    "dimensions": [{"name": "InstanceId", "value": "replace_instance_id_at_runtime"}],
    "threshold": 1,
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "alarm_actions": [ALARM_NOTIFY_TOPIC],
    "evaluation_periods": 1,
    "period": 300,
    "statistic": "Average",
  },
  {
    "alarm_name": "memory full",
    "namespace": "CWAgent",
    "metric_name": "mem_used_percent",
    "dimensions": [{"name": "InstanceId", "value": "replace_instance_id_at_runtime"}],
    "threshold": 75,
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "alarm_actions": [ALARM_NOTIFY_TOPIC],
    "evaluation_periods": 1,
    "period": 300,
    "statistic": "Average",
  },
  {
    "alarm_name": "disk full",
    "namespace": "CWAgent",
    "metric_name": "disk_used_percent",
    "dimensions": [{"name": "InstanceId", "value": "replace_instance_id_at_runtime"}],
    "threshold": 90,
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "alarm_actions": [ALARM_NOTIFY_TOPIC],
    "evaluation_periods": 1,
    "period": 300,
    "statistic": "Average",
  },
  {
    "alarm_name": "high loadaverage",
    "namespace": "System/Detail/Linux",
    "metric_name": "LoadAverage5Min",
    "dimensions": [{"name": "InstanceId", "value": "replace_with_your_instance_id_at_runtime"}],
    "threshold": 5,
    "comparison_operator": "GreaterThanOrEqualToThreshold",
    "alarm_actions": [ALARM_NOTIFY_TOPIC],
    "evaluation_periods": 1,
    "period": 300,
    "statistic": "Average",
  },
]